### ISSUE TITLE
[sight] follow-ups from #3016: dead RELOAD code, missing enforcement-effectiveness CI gate, drain-context race

### ISSUE THREAD

**Issue by jfeng18** [alibaba/anolisa#3021]
PR #3016 reverted the enforcement injection path from RELOAD back to APPEND, fixing the silent fail-open introduced by #2979 (commit 42f5e3b8). Three follow-ups identified during deep review:

### 1. Dead code: `reload_policy_delta` advertises a protocol the kernel does not implement

`ReloadHandle::reload_policy_delta` (ebpf-ifc-engine/src/lib.rs) submits `CAP_REQ_RELOAD_COUNTS/UPDATE/RULE` (tags -1/-2/-3), but the BPF side (`capability.bpf.h` `cap_request_cb`) only handles `CAP_REQ_APPEND_UPDATE(-4)` / `CAP_REQ_APPEND_RULE(-5)`. Unmatched tags fall into the normal-delta arm, get misread as `caller_pid`, and are silently dropped (`CAP_STAT_DROP`).

The Rust-side doc comment actively advertises RELOAD as "the correct path for an external trusted enforcer" — the next caller hits the same fail-open trap.

**Action**: either implement the -1/-2/-3 handlers in BPF, or delete `reload_policy_delta` (and the 0005 actplane patch section that adds it). If the SecCore/AP-02 scenario (#2979's motivation) still needs a non-authority-gated path, it needs a real BPF counterpart, not a userspace stub.

### 2. CI has no enforcement-effectiveness assertion — how the fail-open shipped green

`42f5e3b8` passed all CI gates while making enforcement a no-op. Nothing in CI loads the real BPF engine and asserts that an installed binding actually blocks the operation.

**Action**: a root-level e2e test that installs a `block unlink` binding and asserts `rm` fails with `Operation not permitted` (plus a violation row lands). This closes the *class* — any future protocol/permission regression — not just this instance. The PR #3016 author's manual verification table is exactly the shape this test should automate.

### 3. Drain-context race relies on submitter winning getpid

`cap_drain_current` hooks `sys_enter_getpid` on *any* process, so an agent's getpid can drain the ringbuf before the enforcer's self-trigger (`submit_raw` tail `SYS_getpid`) fires. With APPEND this surfaces as a loud failure (`submit_expect_count` never advances → rollback), never a false `Enforced` — but it is still a spurious-install-failure window.

**Action**: eventually replace the self-trigger with a deterministic drain mechanism (dedicated syscall trigger or per-CPU drain). Low priority: today's failure mode is honest.

Context: verified in deep review of #3016 — https://github.com/alibaba/anolisa/pull/3016#pullrequestreview-3128646636 (fail-open evidence chain, APPEND fail-loud semantics).

**Comment by jfeng18** [comment]
## Follow-up investigation: why `enforce_path_truncate` fails to load on stock 6.x

Investigated the demo failure on ECS (kernel 6.6.102, BPF-LSM active, root) before building the CI gate, since the author verified on 7.1.10 and we needed to know whether the same .o works on 6.x.

### Root cause (verified by minimal reproduction)

It is **not** "LSM programs cannot use bpf_d_path" (my initial reading of the docs was wrong). The distinction is hook-specific trusted-pointer handling:

| Minimal test program | Result on 6.6.102 |
|---|---|
| `lsm/file_open` + `bpf_d_path(&file->f_path, ...)` | **loads OK** — `call bpf_d_path` present in the xlated program |
| `lsm/path_truncate` + `bpf_d_path((struct path*)hook_arg, ...)` | **rejected** — `helper call is not allowed in probe`, byte-identical to the demo failure |

The `path_truncate`/`path_unlink`/`path_rename` hooks pass their `const struct path *` argument as a **BTF-registered trusted pointer** (`trusted_ptr_path`, visible in the verifier log as `arg0 has btf_id 930 type STRUCT 'path'`). The verifier refuses to hand that pointer to `bpf_d_path` directly. In `file_open` the path is reached through a plain field access (`&file->f_path`), which is not a trusted hook argument, so it passes.

The prebuilt `process.bpf.o` routes all three path hooks through `te_handle_file(TE_REF_PATH...)` → `path_to_str()` → `bpf_d_path(hook_arg)`, so all three fail to load on stock 6.x. `file_open` and `file_permission` (which deliberately uses `file_basename` instead, per the comment at process.bpf.c:2062) are unaffected.

Why it passed on the author's 7.1.10 box: that Anolis kernel evidently relaxes the trusted-pointer restriction (or backports a change that does); I cannot verify the 7.1 kernel source, so this part is inference, not verified.

### Implications for the CI gate (#2)

- The gate **can** be built, but the prebuilt object first needs the path-hook fix: `path_truncate`/`path_unlink`/`path_rename` should derive the path without passing the trusted hook pointer to `bpf_d_path` (e.g. `path.dentry` + basename walk, as `file_permission` already does). Until that lands, enforcement only loads on kernels that relax trusted-pointer passing.
- After the fix, the `agent-file-guard` profile becomes loadable on stock 6.x, so the e2e test no longer depends on an Anolis-specific kernel.
- Runner requirements stay the same: BPF-LSM active (`lsm=...,bpf`), root, `ulimit -l unlimited`, BTF available. The current `anolisa-agentsight-ci-x64` container runner likely cannot satisfy this — needs a dedicated host-class runner (the existing `agentsight-runner-test.yml` / nightly precedent applies).

### Incidental finding

When `open_or_install_singleton` fails mid-load, `/sys/fs/bpf/actplane/v1/` keeps an empty `maps/`+`links/` skeleton (`ensure_pinned_engine_dirs` runs before prog load, and the error path does not remove it). Next run recovers because `pinned_engine_present` returns false on missing maps, but the empty dirs linger. Minor, but worth cleaning in the same fix.

Verification artifacts: minimal repro .bpf.c for both cases (file_open pass / path_truncate fail), both load logs, and the demo failure output — all from the same ECS box, reproducible on demand.

**Comment by jfeng18** [comment]
Follow-up 3 is now PR #3264 — the drain race turned out far worse than "low priority" suggested.

**Reproduction (kernel 6.6, ECS, root):** with 4 processes spinning `os.getpid()`, **2841 of 3000** `submit_delta` calls (94.7%) hit `CAP_STAT_DROP` — an agent-dense host makes binding installs effectively broken, not just occasionally flaky.

**Fix:** the drain hook moves `sys_enter_getpid` → `sys_enter_membarrier`, and both self-triggers call `membarrier(QUERY)` (side-effect-free, no agent runtime uses it), so the drain context is deterministically the submitter's own pid. Discriminating test `drain_trigger_survives_getpid_storm` asserts 0 drops under the same getpid storm that broke the old trigger.

With #3263 (follow-up 1), #3260 (follow-up 2) and #3264 (follow-up 3), all three follow-ups are now in review.
