### ISSUE TITLE
[cosh-ng] core: macOS build broken since c818e118 — workspace_fs uses Linux-only openat2/ResolveFlags without platform gating

### ISSUE THREAD

**Issue by SunnyQjm** [alibaba/anolisa#2164]
### Summary

Since commit `c818e118` ("fix(cosh-ng): [core] confine read tools"), `cosh-core` no longer compiles on macOS. The new `crates/cosh-core/src/tool/workspace_fs.rs` uses Linux-only rustix APIs (`openat2`, `ResolveFlags`, `OFlags::PATH`) without any platform gating, and the module is consumed unconditionally by the core read tools (`grep.rs`, `glob.rs`, `list_directory.rs`, `file_patterns.rs`), so the whole crate fails to build.

CI stayed green because the workflow matrix only has Linux runners (`anolisa-k8s-*` / ubuntu); macOS is a developer-local build target and had been building fine right up to the parent of `c818e118` (verified locally at `12ea0ad9`).

### Reproduction

On macOS (verified on darwin arm64, workspace toolchain):

```
cargo build -p cosh-core
```

```
error[E0432]: unresolved imports `rustix::fs::openat2`, `rustix::fs::ResolveFlags`
   --> crates/cosh-core/src/tool/workspace_fs.rs:13:18
    |
 13 | use rustix::fs::{openat2, readlinkat, Dir, FileType, Mode, OFlags, ResolveFlags, CWD};
    |                  ^^^^^^^ no `openat2` in `fs`                      ^^^^^^^^^^^^ no `ResolveFlags` in `fs`

error[E0599]: no associated function or constant named `PATH` found for struct `OFlags`
  --> crates/cosh-core/src/tool/workspace_fs.rs:27:35
    |
 27 | const PIN_FLAGS: OFlags = OFlags::PATH.union(OFlags::CLOEXEC).union(OFlags::NOFOLLOW);

error[E0599]: no associated function or constant named `PATH` found for struct `OFlags`
   --> crates/cosh-core/src/tool/workspace_fs.rs:200:21
    |
200 |             OFlags::PATH | OFlags::DIRECTORY | OFlags::CLOEXEC,
```

`cosh-shell` still builds fine on macOS; only `cosh-core` is affected. Previously built cosh-core binaries keep running — the breakage is compile-time only.

### Impact

- Building cosh-core from source on macOS is impossible at HEAD (no feature flag or workaround; `mod workspace_fs` and its consumers have no `cfg` gating).
- Any workflow that needs an up-to-date local cosh-core binary on macOS (development, real-adapter reproduction/acceptance evidence) is blocked and must fall back to Linux environments.

### Notes on fixing

This is not a one-line `cfg` fix. `workspace_fs` relies on `openat2(RESOLVE_BENEATH | NO_MAGICLINKS | NO_XDEV)` for workspace read confinement, and macOS has no equivalent syscall. A non-Linux fallback needs an explicit security-semantics decision, e.g.:

- component-by-component `openat` walk with `O_NOFOLLOW` (+ manual symlink budget, which the module already tracks via `MAX_SYMLINKS`), or
- a weaker canonicalize-and-prefix-check fallback, documented as best-effort on non-Linux.

Either way the chosen boundary for non-Linux platforms should be stated explicitly rather than silently diverging from the Linux guarantees.

Optionally, a lightweight `cargo check -p cosh-core --target aarch64-apple-darwin` (or a macOS runner smoke job) would catch this class of regression before merge.
